// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KprobeKfreeSkbmem           *ebpf.ProgramSpec `ebpf:"kprobe_kfree_skbmem"`
	KprobeXfrmIncStats          *ebpf.ProgramSpec `ebpf:"kprobe_xfrm_inc_stats"`
	KprobeXfrmStatisticsSeqShow *ebpf.ProgramSpec `ebpf:"kprobe_xfrm_statistics_seq_show"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	IncContext   *ebpf.MapSpec `ebpf:"inc_context"`
	PerfOutput   *ebpf.MapSpec `ebpf:"perf_output"`
	SavedXfrmMib *ebpf.MapSpec `ebpf:"saved_xfrm_mib"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	IncContext   *ebpf.Map `ebpf:"inc_context"`
	PerfOutput   *ebpf.Map `ebpf:"perf_output"`
	SavedXfrmMib *ebpf.Map `ebpf:"saved_xfrm_mib"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.IncContext,
		m.PerfOutput,
		m.SavedXfrmMib,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KprobeKfreeSkbmem           *ebpf.Program `ebpf:"kprobe_kfree_skbmem"`
	KprobeXfrmIncStats          *ebpf.Program `ebpf:"kprobe_xfrm_inc_stats"`
	KprobeXfrmStatisticsSeqShow *ebpf.Program `ebpf:"kprobe_xfrm_statistics_seq_show"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KprobeKfreeSkbmem,
		p.KprobeXfrmIncStats,
		p.KprobeXfrmStatisticsSeqShow,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel_x86.o
var _BpfBytes []byte
