// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfEvent struct {
	Pc             uint64
	Ts             uint64
	Skb            uint64
	Len            uint32
	Mark           uint32
	Netns          uint32
	Ifindex        uint32
	Protocol       uint16
	Payload        [64]uint8
	_              [2]byte
	XfrmIncStackId uint32
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KprobeKfreeSkbmem           *ebpf.ProgramSpec `ebpf:"kprobe_kfree_skbmem"`
	KprobeSkb1                  *ebpf.ProgramSpec `ebpf:"kprobe_skb_1"`
	KprobeSkb2                  *ebpf.ProgramSpec `ebpf:"kprobe_skb_2"`
	KprobeSkb3                  *ebpf.ProgramSpec `ebpf:"kprobe_skb_3"`
	KprobeSkb4                  *ebpf.ProgramSpec `ebpf:"kprobe_skb_4"`
	KprobeSkb5                  *ebpf.ProgramSpec `ebpf:"kprobe_skb_5"`
	KprobeXfrmIncStats          *ebpf.ProgramSpec `ebpf:"kprobe_xfrm_inc_stats"`
	KprobeXfrmStatisticsSeqShow *ebpf.ProgramSpec `ebpf:"kprobe_xfrm_statistics_seq_show"`
	KretprobeKfreeSkbmem        *ebpf.ProgramSpec `ebpf:"kretprobe_kfree_skbmem"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	IncContext   *ebpf.MapSpec `ebpf:"inc_context"`
	PerfOutput   *ebpf.MapSpec `ebpf:"perf_output"`
	Stacks       *ebpf.MapSpec `ebpf:"stacks"`
	Tid2incEvent *ebpf.MapSpec `ebpf:"tid2inc_event"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	IncContext   *ebpf.Map `ebpf:"inc_context"`
	PerfOutput   *ebpf.Map `ebpf:"perf_output"`
	Stacks       *ebpf.Map `ebpf:"stacks"`
	Tid2incEvent *ebpf.Map `ebpf:"tid2inc_event"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.IncContext,
		m.PerfOutput,
		m.Stacks,
		m.Tid2incEvent,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KprobeKfreeSkbmem           *ebpf.Program `ebpf:"kprobe_kfree_skbmem"`
	KprobeSkb1                  *ebpf.Program `ebpf:"kprobe_skb_1"`
	KprobeSkb2                  *ebpf.Program `ebpf:"kprobe_skb_2"`
	KprobeSkb3                  *ebpf.Program `ebpf:"kprobe_skb_3"`
	KprobeSkb4                  *ebpf.Program `ebpf:"kprobe_skb_4"`
	KprobeSkb5                  *ebpf.Program `ebpf:"kprobe_skb_5"`
	KprobeXfrmIncStats          *ebpf.Program `ebpf:"kprobe_xfrm_inc_stats"`
	KprobeXfrmStatisticsSeqShow *ebpf.Program `ebpf:"kprobe_xfrm_statistics_seq_show"`
	KretprobeKfreeSkbmem        *ebpf.Program `ebpf:"kretprobe_kfree_skbmem"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KprobeKfreeSkbmem,
		p.KprobeSkb1,
		p.KprobeSkb2,
		p.KprobeSkb3,
		p.KprobeSkb4,
		p.KprobeSkb5,
		p.KprobeXfrmIncStats,
		p.KprobeXfrmStatisticsSeqShow,
		p.KretprobeKfreeSkbmem,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel_x86.o
var _BpfBytes []byte
